/**
 * Prompd Auto-Fix Utility
 * Detects and fixes common syntax errors in .prmd files,
 * especially those generated by LLMs that don't follow the exact spec.
 */

import YAML from 'yaml'

export interface AutoFixResult {
  fixed: string
  applied: FixApplied[]
  errors: string[]
}

export interface FixApplied {
  type: FixType
  description: string
  line?: number
}

export type FixType =
  | 'add-frontmatter-start'
  | 'add-frontmatter-end'
  | 'convert-params-to-array'
  | 'quote-string-values'
  | 'fix-param-name-format'
  | 'normalize-whitespace'

/**
 * Detects if text appears to be a prompd file that needs fixing
 */
export function needsFix(text: string): boolean {
  const trimmed = text.trim()

  // Missing opening ---
  if (!trimmed.startsWith('---') && looksLikePrompdContent(trimmed)) {
    return true
  }

  // Has frontmatter but may have issues
  if (trimmed.startsWith('---')) {
    const endIndex = trimmed.indexOf('---', 3)
    if (endIndex > 3) {
      const frontmatter = trimmed.substring(3, endIndex).trim()
      try {
        const parsed = YAML.parse(frontmatter)
        if (parsed?.parameters && !Array.isArray(parsed.parameters)) {
          return true // Object format params need conversion
        }
      } catch {
        return true // YAML error needs fixing
      }
    }
  }

  return false
}

/**
 * Check if text looks like prompd content (has typical fields)
 */
function looksLikePrompdContent(text: string): boolean {
  const patterns = [
    /^id\s*:/m,
    /^name\s*:/m,
    /^parameters\s*:/m,
    /^version\s*:/m,
    /^provider\s*:/m,
    /^model\s*:/m,
    /^description\s*:/m
  ]

  // If it has 2+ typical prompd fields, it's likely prompd content
  const matches = patterns.filter(p => p.test(text)).length
  return matches >= 2
}

/**
 * Auto-fix common syntax errors in prompd content
 */
export function autoFix(text: string): AutoFixResult {
  const applied: FixApplied[] = []
  const errors: string[] = []
  let result = text

  // Step 1: Ensure frontmatter delimiters exist
  result = fixFrontmatterDelimiters(result, applied)

  // Step 2: Parse and fix YAML issues
  result = fixYamlContent(result, applied, errors)

  // Step 3: Normalize whitespace
  result = normalizeWhitespace(result, applied)

  return { fixed: result, applied, errors }
}

/**
 * Ensure frontmatter has opening and closing ---
 */
function fixFrontmatterDelimiters(text: string, applied: FixApplied[]): string {
  let result = text.trim()

  // Check for missing opening ---
  if (!result.startsWith('---')) {
    // Look for typical frontmatter content at start
    if (looksLikePrompdContent(result)) {
      result = '---\n' + result
      applied.push({
        type: 'add-frontmatter-start',
        description: 'Added opening --- frontmatter delimiter',
        line: 1
      })
    }
  }

  // Ensure closing --- exists
  if (result.startsWith('---')) {
    const lines = result.split(/\r?\n/)
    let closingIndex = -1
    let inFrontmatter = true

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim()

      // Found closing delimiter
      if (line === '---') {
        closingIndex = i
        break
      }

      // Found markdown header - frontmatter should have ended
      if (line.startsWith('# ')) {
        // No closing --- found before content
        if (inFrontmatter) {
          // Insert --- before the markdown header
          lines.splice(i, 0, '---')
          applied.push({
            type: 'add-frontmatter-end',
            description: 'Added closing --- frontmatter delimiter',
            line: i + 1
          })
          result = lines.join('\n')
        }
        break
      }
    }
  }

  return result
}

/**
 * Parse and fix YAML content issues
 */
function fixYamlContent(text: string, applied: FixApplied[], errors: string[]): string {
  // Extract frontmatter
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!match) return text

  const frontmatterText = match[1]
  const afterFrontmatter = text.substring(match[0].length)

  try {
    const parsed = YAML.parse(frontmatterText)
    if (!parsed) return text

    let modified = false

    // Fix 1: Convert parameters from object to array format
    if (parsed.parameters && !Array.isArray(parsed.parameters) && typeof parsed.parameters === 'object') {
      const paramsArray: any[] = []

      for (const [key, value] of Object.entries(parsed.parameters)) {
        if (typeof value === 'object' && value !== null) {
          // Object format: { csv_data: { type: string, ... } }
          paramsArray.push({
            name: key,
            ...value
          })
        } else if (typeof value === 'string') {
          // Shorthand format: { csv_data: string }
          paramsArray.push({
            name: key,
            type: value
          })
        }
      }

      parsed.parameters = paramsArray
      modified = true
      applied.push({
        type: 'convert-params-to-array',
        description: 'Converted parameters from object to array format (added - name: syntax)'
      })
    }

    // Fix 2: Ensure string values with spaces are properly quoted in output
    // This happens automatically when we stringify with YAML

    if (modified) {
      // Stringify back to YAML with proper formatting
      const newFrontmatter = YAML.stringify(parsed, {
        indent: 2,
        lineWidth: 0, // Don't wrap lines
        singleQuote: false,
        defaultKeyType: 'PLAIN',
        defaultStringType: 'QUOTE_DOUBLE'
      })

      return '---\n' + newFrontmatter + '---' + afterFrontmatter
    }

  } catch (e: any) {
    errors.push(`YAML parse error: ${e?.message || e}`)
  }

  return text
}

/**
 * Normalize whitespace and formatting
 */
function normalizeWhitespace(text: string, applied: FixApplied[]): string {
  let result = text

  // Ensure single blank line after frontmatter
  result = result.replace(/---\n{3,}/, '---\n\n')

  // Ensure file ends with newline
  if (!result.endsWith('\n')) {
    result += '\n'
  }

  return result
}

/**
 * Generate quick-fix suggestions for a given issue
 */
export interface QuickFix {
  title: string
  kind: 'quickfix' | 'refactor'
  edit: {
    range: { startLine: number; startColumn: number; endLine: number; endColumn: number }
    newText: string
  }
}

export function getQuickFixesForLine(
  text: string,
  line: number,
  issue: string
): QuickFix[] {
  const fixes: QuickFix[] = []
  const lines = text.split(/\r?\n/)

  // Missing frontmatter delimiter
  if (issue.includes('Missing frontmatter') && line === 1) {
    fixes.push({
      title: 'Add frontmatter delimiters',
      kind: 'quickfix',
      edit: {
        range: { startLine: 1, startColumn: 1, endLine: 1, endColumn: 1 },
        newText: '---\n'
      }
    })
  }

  // Convert object params to array
  if (issue.includes('parameters') && issue.includes('array')) {
    const result = autoFix(text)
    if (result.applied.some(a => a.type === 'convert-params-to-array')) {
      fixes.push({
        title: 'Convert parameters to array format',
        kind: 'quickfix',
        edit: {
          range: { startLine: 1, startColumn: 1, endLine: lines.length, endColumn: lines[lines.length - 1].length + 1 },
          newText: result.fixed
        }
      })
    }
  }

  return fixes
}

/**
 * Fix LLM-generated content before using it
 * This is called when extracting prompd from AI responses
 */
export function fixLLMGeneratedContent(content: string): string {
  const result = autoFix(content)

  if (result.applied.length > 0) {
    console.log('[AutoFix] Applied fixes:', result.applied.map(a => a.description))
  }

  if (result.errors.length > 0) {
    console.warn('[AutoFix] Errors:', result.errors)
  }

  return result.fixed
}